# Generated by Django 4.2.6 on 2023-10-30 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_plantationordermodel_total_grand_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled', models.BooleanField(default=False)),
                ('pay_with_cash', models.BooleanField(default=False)),
                ('otp', models.CharField(default='12345', max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_delivered', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.plantationaddress')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PlantationDeliveries',
                'ordering': ('-date_created',),
            },
        ),
    ]
