# Generated by Django 4.2.6 on 2023-10-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_plantationdelivery_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationdelivery',
            name='order_number',
            field=models.CharField(default='nj', max_length=50),
            preserve_default=False,
        ),
    ]
