# Generated by Django 4.2.6 on 2023-10-30 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_remove_plantationordermodel_order_number'),
        ('delivery', '0003_plantationdelivery_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationdelivery',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.plantationordermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantationdelivery',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
