# Generated by Django 4.2.6 on 2023-10-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=70)),
                ('provice', models.CharField(max_length=70)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
