# Generated by Django 4.2.6 on 2023-11-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_plantationorderitemmodel_product_id'),
        ('suppliers', '0002_remove_plantationsupplier_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationSupplierOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('cellphone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('total_grand_price', models.FloatField(default=0)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.plantationaddress')),
                ('items', models.ManyToManyField(blank=True, to='orders.plantationorderitemmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
