# Generated by Django 4.2.6 on 2023-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_plantationsupplierordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantationsupplierordermodel',
            old_name='paid',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='plantationsupplierordermodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantationsupplierordermodel',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
