# Generated by Django 4.2.6 on 2023-11-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_rename_paid_plantationsupplierordermodel_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantationsupplierordermodel',
            name='total_grand_price',
        ),
    ]
