# Generated by Django 4.2.6 on 2023-11-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_remove_plantationsupplierordermodel_total_grand_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantationsupplierordermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='plantationsupplierordermodel',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='plantationsupplierordermodel',
            name='email',
        ),
    ]
