# Generated by Django 4.2.6 on 2023-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_plantationsupplierordermodel_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantationsupplier',
            old_name='street',
            new_name='street_name',
        ),
        migrations.AddField(
            model_name='plantationsupplier',
            name='street_number',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
