# Generated by Django 4.2.6 on 2023-11-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_rename_street_plantationsupplier_street_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationsupplierordermodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='suppliers.plantationsupplier'),
        ),
    ]
