# Generated by Django 4.2.6 on 2023-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationeventmodel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantationeventmodel',
            name='rate',
            field=models.CharField(default='100%', max_length=5),
        ),
        migrations.AddField(
            model_name='plantationeventmodel',
            name='ticket',
            field=models.CharField(choices=[('G', 'General'), ('V', 'VIP')], default='G', max_length=2),
            preserve_default=False,
        ),
    ]
