# Generated by Django 4.2.6 on 2023-10-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rename_tax_percentage_plantationproduct_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=50)),
                ('shelf', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.plantationproduct')),
            ],
        ),
    ]
