# Generated by Django 4.2.6 on 2023-10-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantationrentalmodel',
            old_name='accepted',
            new_name='pending',
        ),
    ]
