# Generated by Django 4.2.6 on 2023-10-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_accepted_plantationrentalmodel_pending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantationrentalmodel',
            options={'ordering': ('-date_request',)},
        ),
        migrations.AlterField(
            model_name='plantationrentalmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('overdue', 'overdue'), ('returned', 'returned'), ('rejected', 'rejected'), ('collected', 'collected')], max_length=255),
        ),
    ]
