# Generated by Django 4.2.6 on 2023-10-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationWareHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.IntegerField()),
                ('row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantationWarehouseRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlantationWareHouseColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(max_length=50)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelfs', to='inventory.plantationwarehouserow')),
            ],
        ),
    ]
