# Generated by Django 4.2.6 on 2023-10-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_plantationimagevariation'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qauntity', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.plantationproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='PlantationWareHouse',
        ),
        migrations.DeleteModel(
            name='PlantationWareHouseColumn',
        ),
        migrations.DeleteModel(
            name='PlantationWarehouseRow',
        ),
    ]
