# Generated by Django 4.2.6 on 2023-10-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_plantationstock_delete_plantationwarehouse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantationstock',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
