# Generated by Django 4.2.6 on 2023-10-28 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_qauntity_plantationstock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantationstock',
            old_name='total_amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='plantationstock',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
