# Generated by Django 4.2.6 on 2023-10-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_total_amount_plantationstock_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantationstock',
            name='price',
        ),
    ]
