# Generated by Django 4.2.6 on 2023-10-28 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationAppointmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_service_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=50)),
                ('date', models.DateField()),
                ('fumigation_area', models.FloatField(default=0.0)),
                ('price_per_sqm', models.FloatField(default=0.0)),
                ('appointment_done', models.BooleanField(default=False)),
                ('location', models.CharField(default='Cape town offices', max_length=255)),
                ('appointment_service_completed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('fumigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
