# Generated by Django 4.2.6 on 2023-10-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_plantationproduct_supplier'),
        ('cart', '0002_remove_plantationcartmodel_total_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationproductdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.plantationproduct'),
        ),
    ]
