# Generated by Django 4.2.6 on 2023-10-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_plantationuser_is_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantationuser',
            name='as_admin',
        ),
    ]
