# Generated by Django 4.2.6 on 2023-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_plantationuser_as_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationuser',
            name='role',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Staff'), ('D', 'Delivery')], default='G', max_length=5),
            preserve_default=False,
        ),
    ]
