# Generated by Django 4.2.6 on 2023-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_plantationuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationuser',
            name='role',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Staff'), ('D', 'Delivery'), ('N', 'Dismis'), ('A', 'Admin')], max_length=5),
        ),
    ]
