# Generated by Django 4.2.6 on 2023-11-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_plantationuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationuser',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantationuser',
            name='role',
            field=models.CharField(choices=[('G', 'General'), ('S', 'Staff'), ('D', 'Delivery'), ('N', 'Dismis'), ('A', 'Admin'), ('P', 'Supplier')], max_length=5),
        ),
    ]
