# Generated by Django 4.2.6 on 2023-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_plantationorderitemmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationordermodel',
            name='total_grand_price',
            field=models.FloatField(default=0),
        ),
    ]
