# Generated by Django 4.2.6 on 2023-10-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_plantationordermodel_has_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationordermodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
