# Generated by Django 4.2.6 on 2023-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_plantationordermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationorderitemmodel',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
