# Generated by Django 4.2.6 on 2023-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_plantationnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationnotificationstatus',
            name='subject',
            field=models.CharField(default='Appointment', max_length=50),
        ),
    ]
