# Generated by Django 4.2.6 on 2023-10-28 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_plantationnotificationstatus_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationnotificationstatus',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
