# Generated by Django 4.2.6 on 2023-10-28 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_plantationnotificationstatus_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantationnotification',
            options={'ordering': ('-date_time',)},
        ),
        migrations.AlterModelOptions(
            name='plantationnotificationstatus',
            options={'ordering': ('-date_time',)},
        ),
        migrations.AddField(
            model_name='plantationnotification',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
