# Generated by Django 4.2.6 on 2023-10-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationImageVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('rent_price', models.FloatField(default=0.0)),
                ('available', models.BooleanField(default=True)),
                ('tax_percentage', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='suppliers.plantationsupplier')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
