# Generated by Django 4.2.6 on 2023-10-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_tax_percentage_plantationproduct_discount_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantationImageVariation',
        ),
    ]
