# Generated by Django 4.2.6 on 2023-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_plantationproduct_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
