# Generated by Django 4.2.6 on 2023-10-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_plantationproduct_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
