# Generated by Django 4.2.6 on 2023-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_plantationproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
