# Generated by Django 4.2.6 on 2023-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_plantationproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationproduct',
            name='supplier_price',
            field=models.FloatField(default=0.0),
        ),
    ]
